# Generated by Django 5.1.4 on 2024-12-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='flashsale',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productviewhistory',
            options={'ordering': ['id'], 'verbose_name_plural': 'product view histories'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
    ]
