# Generated by Django 5.1.4 on 2025-01-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_flashsale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashsale',
            options={'ordering': ['-id']},
        ),
    ]
