# Generated by Django 5.1.4 on 2025-01-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_flashsale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
