# Generated by Django 5.1.4 on 2024-12-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productviewhistory',
            options={'verbose_name_plural': 'product view histories'},
        ),
    ]
